---
- hosts: all
  become: yes
  tasks: 
   - name: install java
     yum: 
      name: java-1.8.0-openjdk
      state: present
   - name: install tomcat
     yum:
      name: tomcat
      state: present
   - name: install jenkins
     get_url:
      url: http://ftp-nyc.osuosl.org/pub/jenkins/war-stable/2.121.2/jenkins.war
      dest: /usr/share/tomcat/webapps/jenkins.war
   - name: enable and start tomcat
     service:
      name: tomcat
      state: started
      enabled: yes
     
