---
- hosts: all
  become: yes
  tasks:
   - name: install apache on centos
     yum: 
      name: httpd
      state: present
     when: ansible_os_family == "centos rhel fedora"
   - name: install apache on ubuntu
     yum:
      name: apache2
      state: present
     when: ansible_os_family == "ubuntu"
    
